name: CI

on:
  push

jobs:

  test1:
    runs-on: windows-latest
    steps:
      - run: docker run ghcr.io/coturn/coturn:latest

  test2:
    runs-on: macos-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - run: docker run ghcr.io/coturn/coturn:latest